/**
 * Defines the structure for a user choice within a StoryNode.
 */
export interface StoryChoice {
    id: string;             // Unique ID for the choice (e.g., "C1", "C2_A").
    text: string;           // The text the user sees for this choice (e.g., "Flee into the woods").
    nextNodeId?: string;    // The ID of the node this choice leads to (e.g., "N2_A").
  }
  
  /**
   * Defines the comprehensive structure for a single node in the branching narrative tree.
   * This structure is generated by the Orchestrator/Text Agents and enriched by Image/Audio Agents.
   */
  export interface StoryNode {
    id: string;                     // Unique ID for the node (e.g., "root", "N2_A", "E1").
    is_ending: boolean;             // True if this is one of the 6 final ending nodes.
    
    // Content fields (populated by various agents)
    text: string;                   // The main narrative text for the user to read/listen to.
    imageUrl?: string;              // URL to the image generated for this scene (from Image Agent).
    audioUrl?: string;              // URL to the audio narration (MP3) for the 'text' field (from Audio Agent).
    
    // Branching fields
    choices: StoryChoice[];         // Array of available choices the user can make from this node.
    children?: StoryNode[];         // Array of child nodes that branch out from this node (used primarily by the Orchestrator).
  }
  
  /**
   * Defines the structure for the complete story tree returned by the Orchestrator.
   */
  export interface StoryTree {
      root: StoryNode;
      // You might also include a flat map for quick lookup:
      // nodesMap: { [id: string]: StoryNode };
  }