import { generateJsonFromInputs } from "../agents/textAgent.js";
import { StoryConfiguration, StoryDefinition } from "../types/frontend.js";

/**
 * Generates a StoryDefinition using the text agent, from a StoryConfiguration.
 */
export async function generateStoryDefinitionFromConfiguration(
  configuration: StoryConfiguration,
): Promise<StoryDefinition> {
  const instructions = [
    "You are a top-tier narrative designer and showrunner-level storyteller.",
    "Deliver an irresistibly engaging, original, high-concept StoryDefinition that hooks instantly and sustains tension.",
    "Use the configuration to steer voice, scope, and detail. Write like a prize-winning author.",
    "",
    "Return a JSON object exactly matching this TypeScript shape:",
    "",
    "interface StoryDefinition {",
    "  title: string;",
    "  genre: string;",
    "  theme: string;",
    "  tagline: string;",
    "  image?: { alt?: string; prompt?: string; };",
    "  overview: string;",
    "  plot: string;",
    "  conflict: string;",
    "  resolution: string;",
    "  startHook: string;",
    "  endingOptions: Array<{ id: string; title: string; description: string; isCanonical?: boolean }>; ",
    "  protagonist: { id: string; name: string; role: string; description?: string; motivation?: string; backstory?: string; };",
    "  antagonist?: { id: string; name: string; role: string; description?: string; motivation?: string; backstory?: string; };",
    "  supportingCast?: Array<{ id: string; name: string; role: string; description?: string; motivation?: string; backstory?: string; }>;",
    "  location: string;",
    "  worldDescription: string;",
    "  timePeriod: string;",
    "}",
    "",
    "Creative Directives (bar-raisers):",
    "- Hook Magnetism: startHook must be a single, present-tense line (12–22 words) that poses a sharp dilemma, promise, or reversal.",
    "- Specificity > Generality: avoid bland phrases; prefer concrete, surprising details and active verbs.",
    "- Show, Don’t Tell: imply character and world through actions, sensory cues, and consequences.",
    "- Freshness: subvert common tropes in the chosen genre with at least one unexpected angle.",
    "- Stakes & Momentum: plot/conflict should escalate causally; resolution must be earned (no deus ex machina).",
    "- Voice: distinct, polished, cinematic; evocative but precise. Zero clichés, zero filler, zero meta commentary.",
    "",
    "Field Guidance:",
    "- title: 2–6 words, memorable, genre-congruent, no subtitles.",
    "- tagline: 6–12 word punchy logline fragment that teases risk or irony.",
    "- overview: 2–5 sentences: premise, stakes, emotional promise, world vibe.",
    "- plot: 2–4 sentences: act progression with cause/effect beats and rising complications.",
    "- conflict: 1–3 sentences: central opposition (internal + external) made tangible.",
    "- resolution: 1–3 sentences: satisfying, thematically coherent outcome; leave one thread suggestive if genre fits.",
    "- protagonist: complete with motivation and one striking flaw; name must be distinctive.",
    "- antagonist: include when genre implies opposition; give motive that makes sense from their POV.",
    "- supportingCast: 2–4 characters that pressure the protagonist in different ways.",
    "- location & timePeriod: succinct but anchored (e.g., “Neo-Fez, 2089” or “Coastal Asturias, 17th century”).",
    "- worldDescription: 1–3 sentences with one vivid, idiosyncratic detail readers haven’t seen before.",
    "- image: include and optimize for visual storytelling:",
    "  - image.alt: 6–14 words describing the key visual moment (no commas-only lists).",
    "  - image.prompt: cinematic composition prompt with subject, action, environment, mood, color, and lighting cues.",
    "",
    "Ending Options:",
    "- Provide 3–5 endings spanning tonal variety (triumphant, tragic, bittersweet, ironic, ambiguous).",
    "- Exactly one ending must set isCanonical: true (choose the most thematically resonant).",
    "",
    "IDs & Consistency:",
    "- Use lowercase kebab-case for all id fields (e.g., “protagonist-river-savant”).",
    "- Ensure names, places, and motifs stay consistent across fields.",
    "",
    "Configuration Controls (length, density):",
    "- length ‘small’: keep total prose lean; compress sentences; focus on one vivid image per field.",
    "- length ‘medium’: balanced detail with clear arc and color.",
    "- length ‘long’: richer texture and micro-detail, but never rambling.",
    "- density ‘short’: short sentences, high clarity; ‘medium’: varied cadence; ‘dense’: layered clauses, metaphor sparingly.",
    "",
    "Quality Guardrails:",
    "- Avoid clichés, buzzwords, and generic adjectives (e.g., “mysterious,” “dark,” “very”). Replace with precise imagery.",
    "- Use active voice and strong verbs; no passive hedging unless intentional.",
    "- Respect cultural nuance; no stereotypes or insensitive reductions.",
    "",
    "Strict Output Rules:",
    "- Produce a single valid JSON object that exactly matches StoryDefinition.",
    "- Do not include commentary, markdown, or explanations.",
  ].join("\n");

  const { json } = await generateJsonFromInputs<StoryDefinition>(
    { configuration },
    instructions,
  );
  return json;
}


